Repository kubevirt/enhancements, pull requests merged in 2025-01, with the labels that each got.

#1 chore(veps): Add template
  .github/ISSUE_TEMPLATE/vep.md
  README.md
  veps/NNNN-vep-template/vep.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#4 chore(github): Update VEP issue template
  .github/ISSUE_TEMPLATE/vep.md
Labels: size/M, lgtm, release-note-none, approved, dco-signoff: yes

#2 Enhancement: Adding Link State Management for vNICs
  veps/sig-network/link-state-proposal.md
Labels: lgtm, sig/network, release-note-none, size/L, approved, dco-signoff: yes
