Repository kubevirt/enhancements, pull requests merged in 2025-09, with the labels that each got.

#78 VEP 41 follow-up: Update Object Graph alpha/beta requirements
  veps/sig-storage/vm-object-graph.md
Labels: size/M, lgtm, sig/network, approved, sig/storage, dco-signoff: yes

#70 Add VEP for VirtualMachinePool feature
  veps/sig-compute/vm-pool.md
Labels: lgtm, size/L, needs-approver-review, approved, dco-signoff: yes

#73 VEP #62: Generalize Priority Queue for Migrations
  veps/sig-compute/migration-prio-queue.md
Labels: lgtm, size/L, approved, dco-signoff: yes

#87 vm_video_configuration_field.md: update beta and GA feature stage
  veps/sig-compute/vm_video_configuration_field.md
Labels: size/M, lgtm, approved, dco-signoff: yes

#91 VEP 90: Utility Volumes for virt-launcher Pods
  veps/sig-storage/utility-volumes.md
Labels: lgtm, size/L, approved, sig/storage, dco-signoff: yes
