Repository kubevirt/enhancements, pull requests merged in 2025-05, with the labels that each got.

#36 Enhancements: Add Video configuration field for VMs
  veps/sig-compute/vm_video_configuration_field.md
Labels: lgtm, release-note-none, size/L, approved, dco-signoff: yes

#51 Improve vep tracker template
  .github/ISSUE_TEMPLATE/vep.md
Labels: size/M, lgtm, release-note-none, approved, dco-signoff: yes

#52 Fix typo in VEP template
  veps/NNNN-vep-template/vep.md
Labels: lgtm, release-note-none, approved, size/XS, dco-signoff: yes
