Repository kubevirt/enhancements, pull requests merged in 2025-03, with the labels that each got.

#5 Enhancement: Use ImageVolume to mount OCI images as volumes in virt-launcher
  veps/sig-compute/image-volume-proposal.md
Labels: lgtm, release-note-none, size/L, sig/compute, approved, sig/storage, dco-signoff: yes

#22 Add a basic initial PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: lgtm, release-note-none, approved, size/XS, dco-signoff: yes

#28 issue template: excplicitly state the owning SIG
  .github/ISSUE_TEMPLATE/vep.md
Labels: lgtm, release-note-none, approved, size/XS, dco-signoff: yes

#23 Add an initial .gitignore file
  .gitignore
Labels: lgtm, release-note-none, needs-approver-review, approved, size/S, dco-signoff: yes
